version: '2'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
  web:
    build: .
    command: mix phoenix.server
    volumes:
      - ./:/usr/src/app
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
