version: '2'
services:
  db:
    image: postgres:9.4.5
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
  web:
    build: .
    command: mix phoenix.server
    volumes:
      - ./:/usr/src/app
    ports:
      - "4000:4000"
    environment: &ENV
        VIRTUAL_HOST: imagexplain.local
        VIRTUAL_PORT: 4000
        DATABASE_URL: ecto://user:password@db/imagexplain_dev
    depends_on:
      - db

# db: &DB
#   image: postgres:9.4.5
#   ports:
#     - 5432
#   environment:
#     POSTGRES_USER: user
#     POSTGRES_PASSWORD: password
#
#
# # Separate database for testing (since it gets deleted)
# dbTest:
#   <<: *DB
#
#
# local:
#   build: .
#   command: sh -c "mix phoenix.server"
#   ports:
#     - 4000
#   environment: &ENV
#     VIRTUAL_HOST: imagexplain.local
#     VIRTUAL_PORT: 4000
#     DATABASE_URL: ecto://user:password@db/imagexplain_dev
#   volumes:
#       - ./:/usr/src/app
#   links:
#     - db:db
#
# test:
#   build: .
#   command: sh -c "mix test"
#   environment:
#     DATABASE_URL: ecto://user:password@db/imagexplain_dev
#   volumes:
#       - ./:/usr/src/app
#   links:
#     - dbTest:db
